</td><td></td></tr>
<tr class="bottom"><td colspan="4"><img class="ie6_fix" src="images/bar.png" alt="" width="100%" height="11px" /></td></tr>
<tr><td></td><td colspan="2" class="bottom"><a href="index.shtml">home</a> | <a href="chalet.shtml">the chalet</a> | <a href="gallery.shtml">photo gallery</a> | <a href="map.shtml">location</a> | <a href="price.shtml">prices & availability</a> | <a href="terms.shtml">terms & conditions</a> | <a href="contact.shtml">contact</a></td><td></td></tr>
</table>
</body>
<!--[if lte IE 6]>
  <script type="text/javascript" src="ie6_fix.js"></script>
<![endif]-->
</html>