<!doctype html public "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>Chalet Bossetan - Morzine, French Alps</title>
<meta name="description" content="A spacious, contemporary, high-spec chalet with ski in/ski out access and stunning views, sleeping 10 in 5 en suite bedrooms, available to rent self-catered or catered." />
<meta name="keywords" content="morzine, chalet, self-catered, catered, ski, skiing, portes du soleil, france, alps, winter, holiday, bossetan, avoriaz, les gets, chatel, rent, hire, let, en suite, bathroom, ten, sleeps, booking, geneva, airport, large, february" />
<link rel="stylesheet" type="text/css" href="style.css" />
</head>
<body>
<table cellspacing="0" cellpadding="0">
<tr id="png_fix" class="top"><td valign="bottom" width="50%"><img class="ie6_fix" src="images/bar2.png" alt="" width="100%" height="74px" /></td><td width="426px"><a href="index.html"><img class="ie6_fix" src="images/logo.png" alt="Chalet Bossetan"/></a></td><td class="top" width="546px"><div class="container"><img class="ie6_fix" src="images/bar.png" alt="" width="546px" height="11px" /><div class="top"><a href="chalet.html">THE CHALET</a> <a href="gallery.html">GALLERY</a> <a href="map.html">LOCATION</a> <a href="price.html">PRICES</a> <a href="contact.html">CONTACT</a></div></div></td><td class="top" width="50%"><img class="ie6_fix" src="images/bar.png" alt="" width="100%" height="11px" /></td></tr>
<tr><td></td><td colspan="2">
